### ISSUE TITLE
Doesn't build with zstd 1.5.6

### ISSUE THREAD

**Issue by g2p** [koverstreet/bcachefs-tools#496]
Trying to build on ubuntu 25.04, with libzstd-dev 1.5.6+dfsg-2.
I get these errors:

```
    [CC]     libbcachefs/errcode.o
    [SED]    initramfs/hook
    [SED]    dkms/dkms.conf
libbcachefs/errcode.c: In function ‘zstd_err_to_bch_err’:
libbcachefs/errcode.c:94:28: error: ‘ZSTD_error_literals_headerWrong’ undeclared (first use in this function); did you mean ‘BCH_ERR_ZSTD_error_literals_headerWrong’?
   94 | #define ZSTD_error(n) case ZSTD_error_##n:      return BCH_ERR_ZSTD_error_##n;
      |                            ^~~~~~~~~~~
libbcachefs/errcode.h:40:9: note: in expansion of macro ‘ZSTD_error’
   40 |         ZSTD_error(literals_headerWrong)                \
      |         ^~~~~~~~~~
libbcachefs/errcode.c:95:17: note: in expansion of macro ‘ZSTD_ERRS’
   95 |                 ZSTD_ERRS()
      |                 ^~~~~~~~~
libbcachefs/errcode.c:94:28: note: each undeclared identifier is reported only once for each function it appears in
   94 | #define ZSTD_error(n) case ZSTD_error_##n:      return BCH_ERR_ZSTD_error_##n;
      |                            ^~~~~~~~~~~
libbcachefs/errcode.h:40:9: note: in expansion of macro ‘ZSTD_error’
   40 |         ZSTD_error(literals_headerWrong)                \
      |         ^~~~~~~~~~
libbcachefs/errcode.c:95:17: note: in expansion of macro ‘ZSTD_ERRS’
   95 |                 ZSTD_ERRS()
      |                 ^~~~~~~~~
libbcachefs/errcode.c:94:28: error: ‘ZSTD_error_parameter_combination_unsupported’ undeclared (first use in this function); did you mean ‘BCH_ERR_ZSTD_error_parameter_combination_unsupported’?
   94 | #define ZSTD_error(n) case ZSTD_error_##n:      return BCH_ERR_ZSTD_error_##n;
      |                            ^~~~~~~~~~~
libbcachefs/errcode.h:45:9: note: in expansion of macro ‘ZSTD_error’
   45 |         ZSTD_error(parameter_combination_unsupported)   \
      |         ^~~~~~~~~~
libbcachefs/errcode.c:95:17: note: in expansion of macro ‘ZSTD_ERRS’
   95 |                 ZSTD_ERRS()
      |                 ^~~~~~~~~
libbcachefs/errcode.c:94:28: error: ‘ZSTD_error_cannotProduce_uncompressedBlock’ undeclared (first use in this function); did you mean ‘BCH_ERR_ZSTD_error_cannotProduce_uncompressedBlock’?
   94 | #define ZSTD_error(n) case ZSTD_error_##n:      return BCH_ERR_ZSTD_error_##n;
      |                            ^~~~~~~~~~~
libbcachefs/errcode.h:50:9: note: in expansion of macro ‘ZSTD_error’
   50 |         ZSTD_error(cannotProduce_uncompressedBlock)     \
      |         ^~~~~~~~~~
libbcachefs/errcode.c:95:17: note: in expansion of macro ‘ZSTD_ERRS’
   95 |                 ZSTD_ERRS()
      |                 ^~~~~~~~~
libbcachefs/errcode.c:94:28: error: ‘ZSTD_error_stabilityCondition_notRespected’ undeclared (first use in this function); did you mean ‘BCH_ERR_ZSTD_error_stabilityCondition_notRespected’?
   94 | #define ZSTD_error(n) case ZSTD_error_##n:      return BCH_ERR_ZSTD_error_##n;
      |                            ^~~~~~~~~~~
libbcachefs/errcode.h:51:9: note: in expansion of macro ‘ZSTD_error’
   51 |         ZSTD_error(stabilityCondition_notRespected)     \
      |         ^~~~~~~~~~
libbcachefs/errcode.c:95:17: note: in expansion of macro ‘ZSTD_ERRS’
   95 |                 ZSTD_ERRS()
      |                 ^~~~~~~~~
libbcachefs/errcode.c:94:28: error: ‘ZSTD_error_noForwardProgress_destFull’ undeclared (first use in this function); did you mean ‘BCH_ERR_ZSTD_error_noForwardProgress_destFull’?
   94 | #define ZSTD_error(n) case ZSTD_error_##n:      return BCH_ERR_ZSTD_error_##n;
      |                            ^~~~~~~~~~~
libbcachefs/errcode.h:59:9: note: in expansion of macro ‘ZSTD_error’
   59 |         ZSTD_error(noForwardProgress_destFull)          \
      |         ^~~~~~~~~~
libbcachefs/errcode.c:95:17: note: in expansion of macro ‘ZSTD_ERRS’
   95 |                 ZSTD_ERRS()
      |                 ^~~~~~~~~
libbcachefs/errcode.c:94:28: error: ‘ZSTD_error_noForwardProgress_inputEmpty’ undeclared (first use in this function); did you mean ‘BCH_ERR_ZSTD_error_noForwardProgress_inputEmpty’?
   94 | #define ZSTD_error(n) case ZSTD_error_##n:      return BCH_ERR_ZSTD_error_##n;
      |                            ^~~~~~~~~~~
libbcachefs/errcode.h:60:9: note: in expansion of macro ‘ZSTD_error’
   60 |         ZSTD_error(noForwardProgress_inputEmpty)        \
      |         ^~~~~~~~~~
libbcachefs/errcode.c:95:17: note: in expansion of macro ‘ZSTD_ERRS’
   95 |                 ZSTD_ERRS()
      |                 ^~~~~~~~~
libbcachefs/errcode.c:94:28: error: ‘ZSTD_error_sequenceProducer_failed’ undeclared (first use in this function); did you mean ‘BCH_ERR_ZSTD_error_sequenceProducer_failed’?
   94 | #define ZSTD_error(n) case ZSTD_error_##n:      return BCH_ERR_ZSTD_error_##n;
      |                            ^~~~~~~~~~~
libbcachefs/errcode.h:65:9: note: in expansion of macro ‘ZSTD_error’
   65 |         ZSTD_error(sequenceProducer_failed)             \
      |         ^~~~~~~~~~
libbcachefs/errcode.c:95:17: note: in expansion of macro ‘ZSTD_ERRS’
   95 |                 ZSTD_ERRS()
      |                 ^~~~~~~~~
libbcachefs/errcode.c:94:28: error: ‘ZSTD_error_externalSequences_invalid’ undeclared (first use in this function); did you mean ‘BCH_ERR_ZSTD_error_externalSequences_invalid’?
   94 | #define ZSTD_error(n) case ZSTD_error_##n:      return BCH_ERR_ZSTD_error_##n;
      |                            ^~~~~~~~~~~
libbcachefs/errcode.h:66:9: note: in expansion of macro ‘ZSTD_error’
   66 |         ZSTD_error(externalSequences_invalid)
      |         ^~~~~~~~~~
libbcachefs/errcode.c:95:17: note: in expansion of macro ‘ZSTD_ERRS’
   95 |                 ZSTD_ERRS()
      |                 ^~~~~~~~~
make: *** [Makefile:143: libbcachefs/errcode.o] Error 1
```

Should these error codes be added to include/linux/zstd_errors.h?

**Comment by koverstreet** [comment]
fixed
