### ISSUE TITLE
Build is broken since 7fd6c3ffe45b3b42c0bc8a8c5d1387a5e3316a54

### ISSUE THREAD

**Issue by ojab** [koverstreet/bcachefs-tools#183]
GCC-12.2.0, a613340b26ad88801666362d2824118396f34c38 build fine, but 7fd6c3ffe45b3b42c0bc8a8c5d1387a5e3316a54 fails with 
```
$ make
    [CC]     bcachefs.o
In file included from tools-util.h:16,
                 from cmds.h:10,
                 from bcachefs.c:26:
include/linux/kernel.h:282:9: error: expected specifier-qualifier-list before ‘__DECLARE_FLEX_ARRAY’
  282 |         __DECLARE_FLEX_ARRAY(TYPE, NAME)
      |         ^~~~~~~~~~~~~~~~~~~~
libbcachefs/subvolume_types.h:23:9: note: in expansion of macro ‘DECLARE_FLEX_ARRAY’
   23 |         DECLARE_FLEX_ARRAY(struct snapshot_t, s);
      |         ^~~~~~~~~~~~~~~~~~
make: *** [Makefile:114: bcachefs.o] Error 1
```

**Comment by leahneukirchen** [comment]
This is apparently defined in kernel headers since 5.16.

**Comment by ojab** [comment]
Yeah, but I think that bcachefs-tools [should?] use bundled headers anyway
```
$ git grep DECLARE_FLEX_ARRAY
include/linux/kernel.h:#define DECLARE_FLEX_ARRAY(TYPE, NAME) \
include/linux/kernel.h: __DECLARE_FLEX_ARRAY(TYPE, NAME)
libbcachefs/subvolume_types.h:  DECLARE_FLEX_ARRAY(struct snapshot_t, s);
```

**Comment by leahneukirchen** [comment]
I agree it should, but it's defined in `linux/stddef.h`.

The same applies to `BTREE_ITER_ALL_LEVELS`.

**Comment by ptrcnull** [comment]
> The same applies to `BTREE_ITER_ALL_LEVELS`.

what do you mean by that? that name is not mentioned in the Linux 6.5 headers, generated with `make headers` on the kernel source code

it looks to me like it should be in `libbcachefs/btree_types.h`, but the version in the 1.3.4 tarball doesn't have that name *yet* either

**Comment by ptrcnull** [comment]
would that be why 1.3.4 tarball doesn't build then?
```
error[E0425]: cannot find value `BTREE_ITER_ALL_LEVELS` in module `c`
  --> bch_bindgen/src/btree.rs:35:31
   |
35 |         const ALL_LEVELS = c::BTREE_ITER_ALL_LEVELS as u16;
   |                               ^^^^^^^^^^^^^^^^^^^^^ not found in `c`
```

**Comment by koverstreet** [comment]
I see no reference to BTREE_ITER_ALL_LEVELS in the 1.3.4 tarball

**Comment by ptrcnull** [comment]
```
$ curl -s https://evilpiepirate.org/git/bcachefs-tools.git/snapshot/bcachefs-tools-1.3.4.tar.zst | tar xzO bcachefs-tools-1.3.4/rust-src/bch_bindgen/src/btree.rs | grep BTREE_ITER_ALL_LEVELS
        const ALL_LEVELS = c::BTREE_ITER_ALL_LEVELS as u16;
```
idk what else to tell you

**Comment by koverstreet** [comment]
how bizarre, cgit must be serving up something stale - I think I did respin the release for that issue

https://evilpiepirate.org/bcachefs-tools/bcachefs-tools-1.3.4.tar.zst

**Comment by ptrcnull** [comment]
i hope you don't mean moving the release tag by "respin the release" - that's a poor practice that breaks all downstream usage where the release (tarball) is expected to have a certain checksum, such as basically every single Linux distribution

**Comment by leahneukirchen** [comment]
Also the `v1.3.4` tag in this repo still points to it.

Natural numbers are free, just make another release if one was mistagged.

**Comment by koverstreet** [comment]
Fixed by 314ce7d963ef
